name: ForeverLester
favicon: null
layout_spectrum: 0.02784460922703147
typography_spectrum: 0.8086622166447341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5566479209810495
  lightness: 0.7196194522548467
  saturation: 0.4880909214261919
  rhythmicContrast: 0.9392152610234916
purpose: []
